import json

from app.services.openai_client import chat
from app.services.ocr_service import extract_text_from_image

SYSTEM_TEXT = """You are an AI-generated content detection expert.
Analyze the given text and determine whether it was likely written by
a human or generated by an AI (like ChatGPT, Claude, Gemini, etc.).

Look for these AI writing signals:
- Overly formal or uniform sentence structure
- Excessive use of transition phrases ("Furthermore", "Moreover",
  "In conclusion", "It is worth noting")
- Lack of personal anecdotes, specific opinions, or emotional nuance
- Perfect grammar with no natural human imperfections
- Generic, balanced statements that avoid taking strong positions
- Repetitive paragraph structure
- Unnaturally comprehensive coverage of all angles

Look for these human writing signals:
- Personal voice, opinions, colloquialisms
- Natural imperfections and varied sentence length
- Specific personal experiences or unique perspectives
- Emotional language and strong opinions
- Inconsistent formality
- Typos or informal grammar

Return ONLY valid JSON:
{
  "verdict": "ai_generated" | "likely_ai" | "uncertain" | "likely_human" | "human_written",
  "confidence": 0-100,
  "reasoning": "2-3 sentence explanation of key signals detected",
  "signals": {
    "ai_signals": ["list of detected AI-like patterns"],
    "human_signals": ["list of detected human-like patterns"]
  }
}"""

SYSTEM_IMAGE = """You are an AI-generated image detection expert.
Analyze the given image and determine whether it was likely created
by an AI image generator (like Midjourney, DALL-E, Stable Diffusion)
or is a real photograph/human-made artwork.

Look for these AI image signals:
- Unnatural skin textures or lighting
- Distorted or impossible details (extra fingers, merged objects)
- Overly perfect symmetry or composition
- Dreamlike or surreal quality
- Inconsistent shadows or reflections
- Text that is garbled or nonsensical
- Background elements that don't quite make sense

Return ONLY valid JSON:
{
  "verdict": "ai_generated" | "likely_ai" | "uncertain" | "likely_human" | "real_photo",
  "confidence": 0-100,
  "reasoning": "2-3 sentence explanation of key visual signals detected",
  "signals": {
    "ai_signals": ["list of detected AI-like visual patterns"],
    "human_signals": ["list of detected authentic/human signals"]
  }
}"""


async def detect_ai_text(text: str) -> dict:
    """Detect if text was AI-generated."""
    raw = await chat(
        system=SYSTEM_TEXT,
        user=f'Analyze this text for AI generation:\n\n{text[:3000]}',
        temperature=0.0,
        max_tokens=800,
        response_format={'type': 'json_object'},
    )
    try:
        result = json.loads(raw)
        return {
            'verdict': result.get('verdict', 'uncertain'),
            'confidence': float(result.get('confidence', 50)),
            'reasoning': result.get('reasoning', ''),
            'signals': result.get(
                'signals',
                {'ai_signals': [], 'human_signals': []}
            ),
            'input_type': 'text',
        }
    except Exception:
        return {
            'verdict': 'uncertain',
            'confidence': 50.0,
            'reasoning': 'Analysis failed.',
            'signals': {'ai_signals': [], 'human_signals': []},
            'input_type': 'text',
        }


async def detect_ai_image(image_data: str) -> dict:
    """Detect if an image was AI-generated using GPT-4o vision."""
    from openai import AsyncOpenAI

    from app.core.config import settings

    client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

    extracted_text = ''
    try:
        extracted_text = await extract_text_from_image(image_data)
    except Exception:
        extracted_text = ''

    prompt = (
        'Analyze this image carefully and determine if it was '
        'generated by AI or is a real photograph/human-made artwork. '
        + SYSTEM_IMAGE
    )
    if extracted_text:
        prompt += f'\n\nVisible text or OCR clues:\n{extracted_text[:1000]}'

    resp = await client.chat.completions.create(
        model='gpt-4o',
        messages=[{
            'role': 'user',
            'content': [
                {
                    'type': 'text',
                    'text': prompt,
                },
                {
                    'type': 'image_url',
                    'image_url': {
                        'url': f'data:image/jpeg;base64,{image_data}',
                        'detail': 'high',
                    },
                },
            ],
        }],
        max_tokens=800,
        response_format={'type': 'json_object'},
    )

    raw = resp.choices[0].message.content or '{}'
    try:
        result = json.loads(raw)
        return {
            'verdict': result.get('verdict', 'uncertain'),
            'confidence': float(result.get('confidence', 50)),
            'reasoning': result.get('reasoning', ''),
            'signals': result.get(
                'signals',
                {'ai_signals': [], 'human_signals': []}
            ),
            'input_type': 'image',
        }
    except Exception:
        return {
            'verdict': 'uncertain',
            'confidence': 50.0,
            'reasoning': 'Analysis failed.',
            'signals': {'ai_signals': [], 'human_signals': []},
            'input_type': 'image',
        }
