'use client'

import { motion } from 'framer-motion'
import { Bot, Fingerprint, Sparkles } from 'lucide-react'

export function AIDetectionSection() {
  const prob = 73

  return (
    <section id="ai-detection" className="py-24 relative overflow-hidden bg-[#0D0D0D]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-50px' }}
          transition={{ duration: 0.8 }}
          className="relative rounded-[2.5rem] bg-[#141414] border border-[#2A2A2A] p-8 lg:p-16 flex flex-col lg:flex-row items-center gap-12 lg:gap-20 overflow-hidden group shadow-2xl"
        >
          {/* Orange Gradient Left Accent Border (Simulated with absolute div) */}
          <div className="absolute top-0 bottom-0 left-0 w-2 bg-gradient-to-b from-[#FF6B2B] to-[#FF9F1C] opacity-80 group-hover:w-3 group-hover:opacity-100 transition-all duration-300 rounded-l-[2.5rem]" />
          
          {/* Subtle Background Glow */}
          <div className="absolute top-1/2 -left-1/4 -translate-y-1/2 w-96 h-96 bg-[#FF6B2B]/5 rounded-full blur-[100px] pointer-events-none" />

          {/* Left Content */}
          <div className="flex-1 relative z-10 pl-4 lg:pl-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#1A1A1A]/80 border border-[#2A2A2A] mb-8 shadow-sm">
              <Bot className="w-4 h-4 text-[#FF9F1C]" />
              <span className="text-sm font-medium text-[#FF9F1C] tracking-wide uppercase">Bonus Feature</span>
            </div>
            
            <h2 className="font-sans text-4xl lg:text-5xl font-bold text-white mb-6 leading-tight">
              AI Content Detection
            </h2>
            
            <p className="text-xl text-[#A0A0A0] leading-relaxed mb-6">
              Know if the text you're verifying was written by a human or generated by an LLM.
            </p>
            <div className="inline-flex items-center gap-2 text-sm font-medium text-[#FF6B2B] bg-[#FF6B2B]/10 px-4 py-2 rounded-lg border border-[#FF6B2B]/20">
              <Sparkles className="w-4 h-4" />
              Coming soon: Deepfake media detection
            </div>
          </div>

          {/* Right Content - Mockup Meter */}
          <div className="flex-1 w-full max-w-md relative z-10">
            <div className="rounded-2xl bg-[#0D0D0D] border border-[#2A2A2A] p-8 shadow-inner relative overflow-hidden">
              
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-[#FF6B2B]/20 rounded-full blur-2xl" />

              <div className="flex justify-between items-center mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-[#1A1A1A] rounded-lg">
                    <Fingerprint className="w-5 h-5 text-[#FF9F1C]" />
                  </div>
                  <span className="text-white font-medium">Text Origin Analysis</span>
                </div>
                <span className="px-3 py-1 bg-[#1A1A1A] border border-[#2A2A2A] rounded-md text-xs text-[#A0A0A0]">VX-SCAN</span>
              </div>

              <div className="text-center mb-8 relative">
                <p className="text-[#A0A0A0] text-sm mb-2 uppercase tracking-wide">AI Generation Probability</p>
                <div className="flex items-baseline justify-center gap-1">
                  <motion.span 
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    className="text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-[#FF6B2B] to-[#FF9F1C] drop-shadow-[0_0_15px_rgba(255,107,43,0.3)]"
                  >
                    {prob}
                  </motion.span>
                  <span className="text-3xl font-bold text-[#FF9F1C]">%</span>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="relative h-4 rounded-full bg-[#1A1A1A] mb-8 overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  whileInView={{ width: `${prob}%` }}
                  transition={{ duration: 1.5, type: "spring", bounce: 0.2 }}
                  className="absolute top-0 left-0 bottom-0 bg-gradient-to-r from-[#FF6B2B] to-[#FF9F1C] rounded-full shadow-[0_0_15px_rgba(255,107,43,0.5)]"
                />
                {/* Tick Marks */}
                <div className="absolute inset-0 flex justify-between px-1 items-center opacity-30">
                  {[25, 50, 75].map((tick) => (
                    <div key={tick} className="w-0.5 h-full bg-[#0D0D0D]" style={{ left: `${tick}%`, position: 'absolute' }} />
                  ))}
                </div>
              </div>

              <div className="flex justify-between text-xs text-[#A0A0A0] font-mono">
                <span>Human</span>
                <span className="text-[#FF9F1C]">Suspected AI</span>
              </div>
            </div>
          </div>
        </motion.div>

      </div>
    </section>
  )
}
